config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "finances#index"

  resources :finances, only: [:index, :create]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/finance.rb
class Finance < ApplicationRecord

	before_validation :set_finance_date, on: :create

	enum category: [:income, :expense]
	ENUM_ENTITY = {"income" => 0, "expense" => 1}

	scope :finance_expense, -> { where(:category=>1) }
    scope :today, -> { where(:expense_date => Date.today, :category=>1)}
	scope :expense_date, -> { where("? BETWEEN startDate AND endDate", Date.today)}

	def set_finance_date
		self.expense_date = Date.today if self.expense_date.blank?
	end


	def self.search(bill)
	    if bill
	      where('expense_date LIKE ? ' , "%#{bill}%").having("finances.category = 1")
	    else
	      all
	    end
  	end
  	
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception


  # before_action :set_global_search_variable

  # def set_global_search_variable
  #   finances = Finance.search(params[:bill])

  #   p '>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>'
  #   p finances
  #   p '>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>'
  # end

end

app/controllers/finances_controller.rb
class FinancesController < ApplicationController
	before_action :set_new_finance, only: [:index]


	def index
        finances = Finance.search(params[:bill])
		finances = Finance.finance_expense if params[:bill] == "finance_expense"
		finances = Finance.today if params[:bill] == "today"
	    finances  = Finance.all if params[:bill].nil?
		@finances = finances.paginate(page: params[:page]).order("created_at DESC")
		respond_to do |format|
		format.html
		format.json {render json: @finances, status: :ok}
		end 
	end

	def search
    index
    render :index
  end

	def create
		@finance_created = Finance.new(name: params[:finance][:name], desc: params[:finance][:desc], category: params[:category].to_i, amount: params[:finance][:amount])
		# @finance_created = Finance.new(finance_params)
		respond_to do |format|
		  if @finance_created.save
			format.json {render json: @finance_created, status: :created}
			format.js
			format.html {redirect_to root_path, flash: {success: "Fiannce Saved Successfully"}}
		  else
			format.json {render json: @finance_created.errors.full_messages, status: :unprocessable_entity}
			format.js
			format.html {redirect_to fiannces_path, flash: {error: @finance_created.errors.full_messages}}
		  end
		end
	end


	private

	def finance_params(params)
		params.require(:finance).permit(:name, :desc, :amount, :category )
	end

	def set_new_finance
		@finance = Finance.new
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/finances_helper.rb
module FinancesHelper
end

app/views/finances/_action_buttons.html.erb
<div class="row action-button-margins">
    <div class="col-md-3">
      <button type="button" class= "btn btn-outline-primary btn-md" data-toggle="modal" data-target="#ModalAddFinance">Add a new bill</button>
    </div>

    <div class="col-md-3">
      <%= link_to "Show All Bills", root_path, class: "btn btn-outline-primary btn-md" %>
    </div>

    <div class="col-md-3">
      <%= link_to "Show All Expense", finances_path(bill: "finance_expense"), class: "btn btn-outline-primary btn-md" %>
    </div>

    <div class="col-md-3">
      <%= link_to "Today", finances_path(bill: "today"), class: "btn btn-outline-primary btn-md" %>
    </div>
    <div class="col-4">
      <%= form_tag(finances_path, method: :get) do %>
        <%#= text_field_tag :bill, params[:bill], class: 'datepicker' %>
        <%= date_field_tag :bill, params[:bill] %>
        <%= submit_tag 'Search', name: nil ,class: "btn btn-outline-primary btn-md" %>
      <% end %>
    </div>       

</div>


<!-- Modal -->
<div class="modal fade" id="ModalAddFinance" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Finance Transaction</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <div class="errors_invoice">
        </div>
        <%= render "form" %>
      </div>
    </div>
  </div>
</div>

app/views/finances/_form.html.erb
<%= form_for (@finance), html: {class: 'finance_form'}, method: :post, remote: true do |f| %>
  

  <div class="form-group row">
    <%= f.label :name, "Customer Name:", class: "col-4 col-form-label" %>
    <div class="col-8">
      <%= f.text_field :name, required: true, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group row">
    <%= f.label :desc, "Description:", class: "col-4 col-form-label" %>
    <div class="col-8">
      <%= f.text_field :desc, required: true, class: 'form-control' %>
    </div>
  </div>
  
  <div class="form-group row">
   <%= f.label :category, "Finance Category:", class: "col-4 col-form-label" %>
   <div class="col-8">
     <%= select_tag :category,  options_from_collection_for_select(Finance::ENUM_ENTITY, :last, :first ), { :prompt => "Select Status"} %>
     <%#= select_tag :priority,  options_from_collection_for_select(DeskTask::ENUM_PRIORITY, :last, :first, @task.priority ), { :prompt => "Select Status", class: "ui selection tf_dropdown ", onchange: "priority_update('task_#{@task.id}', this)"} %>
   </div>
  </div>

  <div class="form-group row">
   <%= f.label :amount, "Amount:", class: "col-4 col-form-label" %>
   <div class="col-8">
     <%= f.number_field :amount, required: true, class: 'form-control', min: 0 %>
   </div>
  </div>

  <div class="actions">
    <%= f.submit "Submit", class: 'btn btn-primary pull-right'  %>
  </div>

<% end %>

app/views/finances/_table.html.erb
<div class="table_invoice">
  <table class='table table-striped table-bordered table-hover'>
    <thead>
      <tr class="bg-primary">
        <th class="align_center">Invoice Date</th>
        <th class='align_center'>Name</th>
        <th class='align_center'>Desc</th>
        <th class='align_center'>Finance Category</th>
        <th class='align_center'>Amount</th>
      </tr>
    </thead>
    <tbody>
      <% @finances.each do |finance| %>
      <tr>
        <td class="align_center">
          <%= finance.expense_date %>
        </td>
        <td class="align_center">
          <%= finance.name %>
        </td>
        <td class="align_center">
          <%= finance.desc %>
        </td>
        <td class="align_center">
          <%= finance.category %>
        </td>
        <td class="align_center">
          <%= finance.amount %>
          <%#= finance.total_income%>
        </td>
      </tr>
      <% end %>
    </tbody>
    <tfoot>
    </tfoot>
  </table>
</div>
<div class="flickr_pagination pagination-margin">
  <%= will_paginate @finances, container: false %>
</div>

<!-- Modal -->
<div class="modal fade" id="ModalAddCollection" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Collection</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <div class="errors_invoice">
        </div>
        <%#= render "form_collection" %>
      </div>
    </div>
  </div>
</div>

app/views/finances/create.js.erb
toastr.options = {
  "closeButton": false,
  "debug": false,
  "newestOnTop": false,
  "progressBar": false,
  "positionClass": "toast-top-full-width",
  "preventDuplicates": false,
  "onclick": null,
  "showDuration": "100",
  "hideDuration": "5000",
  "timeOut": "5000",
  "extendedTimeOut": "1000",
  "showEasing": "swing",
  "hideEasing": "linear",
  "showMethod": "fadeIn",
  "hideMethod": "fadeOut"
}
<% if  @finance_created.errors.empty? %>
  $('.finance_form')[0].reset();
  $('#ModalAddFinance').modal('hide');
    toastr["success"]('New Bill has been generated successfully.')
   setTimeout(function(){
    window.location.reload(true);
    }, 2000);
<%else%>
  $('.errors_invoice').append('<p class = "error_msg" ><%= @finance_created.errors.full_messages.join(' , ') %></p>');
  setTimeout(function(){
      $('.error_msg').remove();
    }, 3000);
<%end%>

app/views/finances/index.html.erb
<div class="container">
  <%= render "action_buttons" %>
  <%= render "table" %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Task</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>